<?xml version="1.0"?>
<!DOCTYPE company [
<!ELEMENT company (employee)>
    <!ELEMENT employee (firstname,lastname,contactno,email,address)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT contactno (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT address (city,state,zip)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT state (#PCDATA)>
    <!ELEMENT zip (#PCDATA)>
    ]>
<company>
    <employee>
        <firstname>Sagar</firstname>
        <lastname>Basnet</lastname>
        <contactno>9840111999</contactno>
        <email>sagarbasnet0007@gmail.com</email>
        <address>
            <city>Lalitpur</city>
            <state>Bagmati</state>
            <zip>36770</zip>
        </address>
    </employee>
</company>