=== Waterbobble/BCA/Web_Tech/jobs.dtd
<!ELEMENT jobs (job+)>
<!ELEMENT job (Name,Address,Description,Skill)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (City,State,Country)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Skill (#PCDATA)>
<!ATTLIST Name jobid ID #REQUIRED>

=== Waterbobble/BCA/Web_Tech/jobs.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE jobs SYSTEM "jobs.dtd">   

<jobs>
    <job>
        <Name jobid="1">Accoutant</Name>
        <Address>
            <City>Lalitpur</City>
            <State>Bagmati</State>
            <Country>Nepal</Country>
        </Address>
        <Description>This Position is for a junior Accountant.</Description>
        <Skill>-basic accounting </Skill>
    </job>
    <job>
        <Name jobid="2">Front Desk Officer</Name>
        <Address>
            <City>Kathmandu</City>
            <State>Bagmati</State>
            <Country>Nepal</Country>
        </Address>
        <Description>This Position is for a Front Desk Officer.</Description>
        <Skill>Good communication skill </Skill>
    </job>

</jobs>
